program AspTest;
  // wel


{$R *.dres}

uses
  Parnassus.FMXContainer in 'FMX\Parnassus.FMXContainer.pas',
  Parnassus.FMXContainerReg in 'FMX\Parnassus.FMXContainerReg.pas',
  Vcl.Forms,
  Winapi.Windows,
  System.SysUtils,
  System.StrUtils,
  Vcl.Themes,
  Vcl.Styles,
  NzisThreadFull in 'NzisThreadFull.pas',
  ThreadLoadDB in 'ThreadLoadDB.pas',
  DbHelper in 'DbHelper.pas',
  VTREditors in 'VTREditors.pas',
  HistoryNav in 'HistoryNav.pas',
  NZISSuperAddress in 'NZISSuperAddress.pas',
  DlgSuperCert23 in 'DlgSuperCert23.pas',
  FILE_SUBM_PL in 'FILE_SUBM_PL.pas',
  ADB_DataUnit in 'ADB_DataUnit.pas',
  Fmx.HipTypes in 'Fmx.HipTypes.pas',
  ProfForm in 'FMX\ProfForm.pas',
  Table.PatientNew in 'Aspects\Tables\Table.PatientNew.pas',
  Table.PregledNew in 'Aspects\Tables\Table.PregledNew.pas',
  Table.CL050 in 'Aspects\Tables\Table.CL050.pas',
  Table.CL088 in 'Aspects\Tables\Table.CL088.pas',
  Table.CL132 in 'Aspects\Tables\Table.CL132.pas',
  Table.CL134 in 'Aspects\Tables\Table.CL134.pas',
  Table.CL139 in 'Aspects\Tables\Table.CL139.pas',
  Table.CL142 in 'Aspects\Tables\Table.CL142.pas',
  Table.CL022 in 'Aspects\Tables\Table.CL022.pas',
  Table.CL024 in 'Aspects\Tables\Table.CL024.pas',
  Table.CL038 in 'Aspects\Tables\Table.CL038.pas',
  Table.Role in 'Aspects\Tables\Table.Role.pas',
  Table.Unfav in 'Aspects\Tables\Table.Unfav.pas',
  Table.Diagnosis in 'Aspects\Tables\Table.Diagnosis.pas',
  Table.DiagnosticReport in 'Aspects\Tables\Table.DiagnosticReport.pas',
  Table.Doctor in 'Aspects\Tables\Table.Doctor.pas',
  Table.EventsManyTimes in 'Aspects\Tables\Table.EventsManyTimes.pas',
  Table.Exam_boln_list in 'Aspects\Tables\Table.Exam_boln_list.pas',
  Table.ExamImmunization in 'Aspects\Tables\Table.ExamImmunization.pas',
  Table.MDN in 'Aspects\Tables\Table.MDN.pas',
  Table.Mkb in 'Aspects\Tables\Table.Mkb.pas',
  Table.NasMesto in 'Aspects\Tables\Table.NasMesto.pas',
  Table.NomenNzis in 'Aspects\Tables\Table.NomenNzis.pas',
  Table.Oblast in 'Aspects\Tables\Table.Oblast.pas',
  Table.Obshtina in 'Aspects\Tables\Table.Obshtina.pas',
  Table.PatientNZOK in 'Aspects\Tables\Table.PatientNZOK.pas',
  Table.PR001 in 'Aspects\Tables\Table.PR001.pas',
  Table.Practica in 'Aspects\Tables\Table.Practica.pas',
  Table.Procedures in 'Aspects\Tables\Table.Procedures.pas',
  RealObj.RealHipp in 'Aspects\Tables\RealObj.RealHipp.pas',
  ProfGraph in 'Aspects\ProfGraph.pas',
  Table.ExamAnalysis in 'Aspects\Tables\Table.ExamAnalysis.pas',
  RealObj.NzisNomen in 'Aspects\Tables\RealObj.NzisNomen.pas',
  DM in 'DM.pas',
  HistoryThread in 'HistoryThread.pas',
  DBCollection.Patient in 'DBCollections\DBCollection.Patient.pas',
  DBCollection.Pregled in 'DBCollections\DBCollection.Pregled.pas',
  DBCollection.Therapy in 'DBCollections\DBCollection.Therapy.pas',
  DBCollection.Types in 'DBCollections\DBCollection.Types.pas',
  DBCollection.Addres in 'DBCollections\DBCollection.Addres.pas',
  DBCollection.Assessment in 'DBCollections\DBCollection.Assessment.pas',
  DBCollection.Consult in 'DBCollections\DBCollection.Consult.pas',
  DBCollection.Diagnosis in 'DBCollections\DBCollection.Diagnosis.pas',
  DBCollection.Doctor in 'DBCollections\DBCollection.Doctor.pas',
  DBCollection.MedNapr in 'DBCollections\DBCollection.MedNapr.pas',
  Nzis.Types in 'Nzis.Types.pas',
  RoleButton in 'DynWinPanel\RoleButton.pas',
  DynSpeedButton in 'DynWinPanel\DynSpeedButton.pas',
  StatusItem in 'FMX\StatusItem.pas',
  FinderFormFMX in 'FMX\FinderFormFMX.pas',
  X006 in 'X006.pas',
  Table.KARTA_PROFILAKTIKA2017 in 'Aspects\Tables\Table.KARTA_PROFILAKTIKA2017.pas',
  Table.NZIS_QUESTIONNAIRE_RESPONSE in 'Aspects\Tables\Table.NZIS_QUESTIONNAIRE_RESPONSE.pas',
  Table.NZIS_PLANNED_TYPE in 'Aspects\Tables\Table.NZIS_PLANNED_TYPE.pas',
  Table.BLANKA_MED_NAPR in 'Aspects\Tables\Table.BLANKA_MED_NAPR.pas',
  Table.NZIS_ANSWER_VALUE in 'Aspects\Tables\Table.NZIS_ANSWER_VALUE.pas',
  Table.NZIS_QUESTIONNAIRE_ANSWER in 'Aspects\Tables\Table.NZIS_QUESTIONNAIRE_ANSWER.pas',
  Table.NZIS_RESULT_DIAGNOSTIC_REPORT in 'Aspects\Tables\Table.NZIS_RESULT_DIAGNOSTIC_REPORT.pas',
  Table.NZIS_DIAGNOSTIC_REPORT in 'Aspects\Tables\Table.NZIS_DIAGNOSTIC_REPORT.pas',
  Table.CL144 in 'Aspects\Tables\Table.CL144.pas',
  msgX002 in 'XML\msgX002.pas',
  L010 in 'L010.pas',
  CertHelper in 'CertHelper.pas',
  X004 in 'X004.pas',
  AspectPerformerThread in 'AspectPerformerThread.pas',
  x010 in 'x010.pas',
  X014 in 'X014.pas',
  Table.CL037 in 'Aspects\Tables\Table.CL037.pas',
  WalkFunctions in 'WalkFunctions.pas',
  CertThread in 'CertThread.pas',
  Table.Certificates in 'Aspects\Tables\Table.Certificates.pas',
  SearchThread in 'Aspects\SearchThread.pas',
  Nzis.Nomen.baseCL000 in 'Aspects\Nzis.Nomen.baseCL000.pas',
  Aspects.Collections in 'Aspects\Aspects.Collections.pas',
  Aspects.Types in 'Aspects\Aspects.Types.pas',
  RealObj.RealNzis in 'Aspects\RealObj.RealNzis.pas',
  MainRttiExpl in '..\..\Tools\blog-master\RTTI\Rtti Explorer Lite\MainRttiExpl.pas',
  PDFium.Frame in '..\PDFViewer\PDFium.Frame.pas',
  AspectiTest in 'AspectiTest.pas' {Form5},
  New in 'FMX\NewFMX\New.pas',
  RolePanels in '..\Popup\RolePanels.pas',
  TitleBar in '..\Popup\TitleBar.pas',
  RoleBar in '..\Popup\RoleBar.pas',
  OptionsForm in '..\Popup\OptionsForm.pas',
  FMX.GifUtils in 'C:\Users\Administrator1\Downloads\FMXGif\FMX.GifUtils.pas';

{$R *.res}

{$SetPEFlags IMAGE_FILE_LARGE_ADDRESS_AWARE}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm5, Form5);
  Application.Run;
end.
